### ISSUE TITLE
Bad link in readme.md

### ISSUE THREAD

**Issue by cdluv** [gz/rust-uio#2]
Clicking on your first link in your readme.md file, which links to (https://www.kernel.org/doc/htmldocs/uio-howto/  gives a 404.

Really interested in what you're doing, so having a link you've referenced is certainly important for context.  Thanks for sharing your code :-)

**Comment by gz** [comment]
Thanks for letting me know. The page seems to have moved from accessing it last time and can now be found here: https://www.kernel.org/doc/html/latest/driver-api/uio-howto.html

I updated the README.
