### ISSUE TITLE
relax cargo dep version pinning

### ISSUE THREAD

**Issue by lriesebos** [gz/rust-uio#4]
Hi @gz , Is this project still active? If so, I was wondering if the cargo dependency version pins can be relaxed or package versions can be bumped. especially the `nix` package, which seems to have a security issue. see the screenshot below.

![image](https://github.com/gz/rust-uio/assets/28567817/2692cbbc-6959-4f05-99a0-4d042b8ee83b)

**Comment by gz** [comment]
I believe this was fixed in 0.2.1, otherwise feel free to reopen this
